-- =============================================================================
-- Migração 070 — Fotos de demonstração da biblioteca padrão GestAcad
--
-- Anexa a foto do movimento (início do exercício) a cada exercício da
-- biblioteca padrão semeada na 069. Fonte: free-exercise-db
-- (github.com/yuhonas/free-exercise-db) — licença Unlicense (domínio público,
-- uso comercial livre). O domínio raw.githubusercontent.com já está liberado
-- em next.config.mjs.
--
-- Só toca nos treinos-modelo de plataforma ('gestacad-%', academia_id NULL) e
-- só quando o exercício ainda está sem imagem — não altera treino de academia,
-- de instrutor nem ficha de aluno. Reexecutável.
--
-- "Burpee" não tem equivalente no banco livre e segue sem foto (o instrutor
-- pode subir um clipe próprio). Vídeos curtos licenciados entrarão numa
-- migração futura, se/quando a fonte for contratada.
--
-- Mapeamento PT→EN conferido item a item; URLs validadas (HTTP 200).
-- =============================================================================

update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Crunch/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Abdominal Infra' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ab_Crunch_Machine/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Abdominal Supra' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Thigh_Abductor/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Abdução no Cabo' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Afundo Alternado' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Side_Split_Squat/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Agachamento Búlgaro' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Full_Squat/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Agachamento Livre' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plie_Dumbbell_Squat/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Agachamento Sumô' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Agachamento com Peso' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Freehand_Jump_Squat/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Agachamento com Salto' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Lunge/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Avanço' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pullups/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Barra Fixa' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Thigh_Abductor/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Cadeira Abdutora' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Thigh_Adductor/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Cadeira Adutora' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Cadeira Extensora' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Cadeira Extensora (leve)' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Leg_Curl/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Cadeira Flexora' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Crossover' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Machine_Flyes/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Crucifixo Inverso' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Flyes/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Crucifixo com Halteres' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Butterfly/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Crucifixo na Máquina' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shoulder_Press/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Desenvolvimento Militar' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Shoulder_Military_Press/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Desenvolvimento Máquina' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Desenvolvimento com Halteres' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Dumbbell_Raise/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Elevação Frontal' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Elevação Lateral' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Elevação Lateral (leve)' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Elevação Pélvica' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shrug/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Encolhimento' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Glute_Kickback/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Glúteo no Cabo' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hack_Squat/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Hack' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Leg Press 45°' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Leg Press 45° (leve)' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Dips/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Mergulho no Banco' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Mesa Flexora' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Mountain_Climbers/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Mountain Climber' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Calf_Raise/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Panturrilha Sentado' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Panturrilha em Pé' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Star_Jump/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Polichinelo' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Prancha Isométrica' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Pulldown' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Puxada Frontal' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Remada Baixa' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Remada Curvada' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Remada Curvada com Barra' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Remada Sentada' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Dumbbell_Row/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Remada Unilateral' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternate_Incline_Dumbbell_Curl/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Rosca Alternada' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Rosca Direta' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Rosca Direta com Barra' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hammer_Curls/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Rosca Martelo' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Preacher_Curl/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Rosca Scott' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stiff-Legged_Barbell_Deadlift/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Stiff' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Incline_Bench_Press_-_Medium_Grip/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Supino Inclinado com Barra' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Press/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Supino Inclinado com Halteres' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Chest_Press/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Supino Máquina' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Chest_Press/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Supino Máquina (leve)' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Chest_Press/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Supino Reto Máquina' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Supino Reto com Barra' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown_-_Rope_Attachment/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Tríceps Corda' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Tríceps Pulley' and coalesce(e.imagem_demonstracao_url,'') = '';
update public.exercicios_treino e set imagem_demonstracao_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Triceps_Press/0.jpg' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Tríceps Testa' and coalesce(e.imagem_demonstracao_url,'') = '';
