-- =============================================================================
-- Migração 071 — Vídeos de demonstração na biblioteca padrão GestAcad
--
-- Liga os 16 clipes curtos que já existem em public/videos/catalogo/*.mp4
-- (356–959 KB cada, MP4) aos exercícios equivalentes da biblioteca padrão (069).
-- Cobre 20 nomes de exercício.
--
-- Sem sobrecarregar o banco: guarda só o CAMINHO relativo ('/videos/catalogo/…'),
-- ~30 caracteres. Nenhum arquivo novo é adicionado — reaproveita os clipes que
-- já estão no deploy (mesmo padrão da migration 054).
--
-- Só toca nos modelos de plataforma ('gestacad-%') e só quando o exercício
-- ainda está sem vídeo. A foto (migration 070) continua como fallback nos
-- exercícios sem clipe. Reexecutável.
-- =============================================================================

update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/leg-press-45.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Leg Press 45°' and coalesce(e.video_demonstracao_url,'') = '';
update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/leg-press-45.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Leg Press 45° (leve)' and coalesce(e.video_demonstracao_url,'') = '';
update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/supino-reto-barra.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Supino Reto com Barra' and coalesce(e.video_demonstracao_url,'') = '';
update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/supino-inclinado-halteres.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Supino Inclinado com Halteres' and coalesce(e.video_demonstracao_url,'') = '';
update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/desenvolvimento-halteres.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Desenvolvimento com Halteres' and coalesce(e.video_demonstracao_url,'') = '';
update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/elevacao-lateral.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Elevação Lateral' and coalesce(e.video_demonstracao_url,'') = '';
update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/elevacao-lateral.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Elevação Lateral (leve)' and coalesce(e.video_demonstracao_url,'') = '';
update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/rosca-direta-barra.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Rosca Direta' and coalesce(e.video_demonstracao_url,'') = '';
update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/rosca-direta-barra.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Rosca Direta com Barra' and coalesce(e.video_demonstracao_url,'') = '';
update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/rosca-martelo.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Rosca Martelo' and coalesce(e.video_demonstracao_url,'') = '';
update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/rosca-scott.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Rosca Scott' and coalesce(e.video_demonstracao_url,'') = '';
update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/triceps-corda.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Tríceps Corda' and coalesce(e.video_demonstracao_url,'') = '';
update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/triceps-testa.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Tríceps Testa' and coalesce(e.video_demonstracao_url,'') = '';
update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/cadeira-flexora.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Cadeira Flexora' and coalesce(e.video_demonstracao_url,'') = '';
update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/panturrilha-em-pe.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Panturrilha em Pé' and coalesce(e.video_demonstracao_url,'') = '';
update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/elevacao-pelvica.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Elevação Pélvica' and coalesce(e.video_demonstracao_url,'') = '';
update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/mergulho-no-banco.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Mergulho no Banco' and coalesce(e.video_demonstracao_url,'') = '';
update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/remada-baixa-cabo.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Remada Baixa' and coalesce(e.video_demonstracao_url,'') = '';
update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/afundo-passada.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Avanço' and coalesce(e.video_demonstracao_url,'') = '';
update public.exercicios_treino e set video_demonstracao_url = '/videos/catalogo/afundo-passada.mp4' from public.treinos t where e.treino_id = t.id and t.academia_id is null and t.visibilidade = 'plataforma' and t.codigo_importacao like 'gestacad-%' and e.nome_exercicio = 'Afundo Alternado' and coalesce(e.video_demonstracao_url,'') = '';
